on:
  push:
  pull_request:
  schedule:
    - cron:  '0 1 * * *' # Run every morning at 01:00. Ref https://crontab.guru/examples.html
name: Scrape Data
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Build
      run: pip install -r requirements.txt
    - name: Scrape
      run: scrapy crawl kvikmyndir_is 
    - uses: mikeal/publish-to-github-action@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you